config/routes.rb
Rails.application.routes.draw do

  get 'nutrition/index'

  resources :recipes
  resources :biometrics
  resources :nutrition
  root 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get 'viewall' => 'recipes#view'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients

  def recipe_payload
    {
      id: id,
      name: name,
      protein: protein,
      carbohydrate: carbohydrate,
      fat: fat,
      calories: calories,
      category: category,
      image: image,
    }
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authorize
  before_action :set_recipe, only: :show
  before_action :set_ingredients, only: :show


  def index
    @biometric = current_user.biometric

    @diet = @biometric.diet

    @recipes = basic_recipe || atkins_recipe || paleo_recipe || vegan_recipe

    @chosen_recipe = @recipes.shuffle
    @chosen_recipe = diet_map[@diet]
    # @chosen_recipe = @chosen_recipe.shuffle
    @chosen_recipe.uniq! { |recipe| recipe[:category] }

    @suggested_foods = Nutrition.where(@biometric.pretty_conditions.merge(good_for_you: true))
    @not_suggested_foods = Nutrition.where(@biometric.pretty_conditions.merge(good_for_you: false))
  end

  ## TODO: move to recipe model
  def vegan_recipe
    Recipe.where(vegan: true).map { |n| n.recipe_payload }
  end

  def basic_recipe
    Recipe.where(basic: true).map { |n| n.recipe_payload }
  end

  def paleo_recipe
    Recipe.where(paleo: true).map { |n| n.recipe_payload }
  end

  def atkins_recipe
    Recipe.where(atkins: true).map { |n| n.recipe_payload }
  end

  def show
    @foods = Food.where(ingredients: {id: @ingredients.pluck(:id)}).joins(:ingredients)
  end

  def view
    @biometric = current_user.biometric

    @diet = @biometric.diet

    @recipes = basic_recipe || atkins_recipe || paleo_recipe || vegan_recipe

    @chosen_recipe = @recipes.shuffle
    @chosen_recipe = diet_map[@diet]
  end


  private

  def diet_map
    {
      "1" => basic_recipe,
      "2" => atkins_recipe,
      "3" => paleo_recipe,
      "4" => vegan_recipe
    }
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_ingredients
    @ingredients = Ingredient.where(recipe_id: @recipe.id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class=container-fluid id="header">
  <div class="row">
    <div class="col-md-6 col-md-offset-3" id="header_text">
      <h2><center>Your Customized Nutrition Plan</center></h2><br>
      <center><p>Based on the diet that you selected, we have provided an example of meals for one day. <br><em>Portion sizes may vary depending on body type and exercise.</em></p></center>
    </div>
  </div>
</div>
<br><br>

<div class="recipes-wrap">
  <div class="container">
    <div class="row">
      <div class="recipes-header">
        <center><h4>Daily Meals (Sample)</h4></center>
      </div>
      <% @chosen_recipe.each do |recipe| %>
        <%= link_to recipe_path(recipe), class: 'recipe-wrapper' do %>
          <%= image_tag "http://placehold.it/250x250", class: 'recipe-img' %>
          <div class="recipe-meta">
            <h5><%= recipe[:name] %></h5>
            <span class="meal-cat"><b>Category:</b> <%= recipe[:category] %></span>
            <span><b>Calories:</b> <%= recipe[:calories] %></span>
            <span><b>Protein:</b> <%= recipe[:protein] %></span>
            <span><b>Fat:</b> <%= recipe[:fat] %></span>
            <span><b>Carbohydrate:</b> <%= recipe[:carbohydrate] %></span>
          </div>
        <% end %>
      <% end %>
      <div class=container-fluid>
        <div class="row">
          <div class="col-md-4 col-md-offset-1 pull-right">
            <h4><%= link_to "View More Recipes >>", viewall_path %></h4>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="suggested-foods row">
      <div class="col-md-5 col-md-offset-1">
        <center><h4>Suggested Foods</h4></center>
      </div>
      <div class="col-md-4">
        <center><h4>Food to Stay Away From</h4></center>
      </div>
      <div class="col-md-5 col-md-offset-1">
        <% @suggested_foods.each do |food| %>
        <center><%= food.name %></center>
        <% end %>
      </div>
      <div class="col-md-4">
        <% @not_suggested_foods.each do |food| %>
        <center><%= food.name %></center>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/recipes/show.html.erb
<div class=container-fluid id="recipe_header">
  <div class="row">
    <div class="col-md-8 col-md-offset-2" id="recipe_text">
      <h1 id="title_text"><center><%= @recipe.name %></center></h1>
    </div>
  </div>
</div>
<br>
<div class=container>
  <div class="row">
    <div class="col-md-5 recipe-ingredients">
      <h3>Ingredients</h3>
      <div class="form-check">
        <% @foods.each do |food| %>
          <li>
            <%= check_box_tag(food.id, food.name) %>
            <%= label_tag(food.id, food.name, :class => 'checkbox-primary') %>
          </li>
        <% end %>
      </div>
    </div>
    <div class="col-md-7">
      <center><h3>Instructions</h3></center>
      <center><%= @recipe.instructions %></center>
    </div>
  </div>
</div>
<br>
<div class=container-fluid>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h5><center><%= link_to 'Back to Nutrition Plan', recipes_path, class:"btn btn-default new_button" %></center></h5>
    </div>
  </div>
</div>

app/views/recipes/view.html.erb
<div class=container-fluid id="header">
  <div class="row">
    <div class="col-md-6 col-md-offset-3" id="header_text">
      <h2><center>Recipes For Your Diet</center></h2>
    </div>
  </div>
</div>
<br><br>

<div class="recipes-wrap">
  <div class="container">
    <div class="row">
      <div class="recipes-header">
        <center><h4>Daily Meals (Sample)</h4></center>
      </div>
      <% @chosen_recipe.each do |recipe| %>
        <%= link_to recipe_path(recipe), class: 'recipe-wrapper' do %>
          <%= image_tag "http://placehold.it/250x250", class: 'recipe-img' %>
          <div class="recipe-meta">
            <h5><%= recipe[:name] %></h5>
            <span class="meal-cat"><b>Category:</b> <%= recipe[:category] %></span>
            <span><b>Calories:</b> <%= recipe[:calories] %></span>
            <span><b>Protein:</b> <%= recipe[:protein] %></span>
            <span><b>Fat:</b> <%= recipe[:fat] %></span>
            <span><b>Carbohydrate:</b> <%= recipe[:carbohydrate] %></span>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-4 col-md-offset-4">
      <h5><center><%= link_to 'Back To Nutrition Plan', recipes_path, class:"btn btn-default new_button" %></center></h5>
    </div>
  </div>
  </div>
</div>

<!-- <div class=container-fluid>
  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <h4>Name</h4>
    </div>
    <div class="col-md-1">
      <h4>Meal</h4>
    </div>
    <div class="col-md-1">
      <h4>Protein</h4>
    </div>
    <div class="col-md-1">
      <h4>Fat</h4>
    </div>
    <div class="col-md-2">
      <h4>Carbohydrates</h4>
    </div>
    <div class="col-md-1">
      <h4>Calories</h4>
    </div>
  </div>
</div>


<div class=container-fluid>
  <div class="row">
    <div class="col-md-4 col-md-offset-1">
      <% @chosen_recipe.each do |recipe| %>
        <h5><%= link_to recipe[:name], recipe_path(recipe) %></h5>
        <% end %>
    </div>
    <div class="col-md-1">
      <% @chosen_recipe.each do |recipe| %>
        <h5><%= recipe[:category] %></h5>
        <% end %>
    </div>
    <div class="col-md-1">
      <% @chosen_recipe.each do |recipe| %>
        <h5><%= recipe[:protein] %></h5>
        <% end %>
    </div>
    <div class="col-md-1">
      <% @chosen_recipe.each do |recipe| %>
        <h5><%= recipe[:fat] %></h5>
        <% end %>
    </div>
    <div class="col-md-2 ">
      <% @chosen_recipe.each do |recipe| %>
        <h5><%= recipe[:carbohydrate] %></h5>
        <% end %>
    </div>
    <div class="col-md-1">
      <% @chosen_recipe.each do |recipe| %>
        <h5><%= recipe[:calories] %></h5>
        <% end %>
    </div>
  </div>
</div> -->

<!-- <div class=container-fluid>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h5><center><%= link_to 'Back To Nutrition Plan', recipes_path, class:"btn btn-default new_button" %></center></h5>
    </div>
  </div>
</div> -->