config/routes.rb
Rails.application.routes.draw do

  get 'nutrition/index'

  resources :recipes
  resources :biometrics
  resources :nutrition
  root 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get 'viewall' => 'recipes#view'
end

app/models/biometric.rb
class Biometric < ApplicationRecord
  belongs_to :user

  def pretty_conditions
    conditions_hash = {}
    if diet == '4'
      conditions_hash[:vegan] = true
    elsif diet == '3'
      conditions_hash[:paleo] = true
    elsif diet == '2'
      conditions_hash[:atkins] = true
    elsif diet == '1'
      conditions_hash[:basic] = true
    end

    if body_type == '3'
      conditions_hash[:endomorphs] = true
    elsif body_type == '2'
      conditions_hash[:mesomorphs] = true
    elsif body_type == '1'
      conditions_hash[:ectomorphs] = true
    end

    conditions_hash
  end

  def to_kg(n)
    n * 0.453592
  end

  def pfc_ratio(dac, lbm, bf)
    protein_calories = (35 * dac) / 100
    carbs_calories = (45 * dac) / 100
    fat_calories = (20 * dac) / 100
    {
      "dac" => dac,
      "lbm" => lbm,
      "bf" => bf,
      "protein_calories" => protein_calories,
      "carbs_calories" => carbs_calories,
      "fat_calories" => fat_calories,
      "protein_grams" => protein_calories / 4,
      "carbs_grams" => carbs_calories / 4,
      "fat_grams" => fat_calories / 9
    }
  end

  def male_dac_calculator
    if self.waist_size.nil? && self.neck.nil?
      bmr = (9.99 * self.current_weight) + (6.25 * self.height) - (4.92 *self.age) + 5 # Mifflins-St-Joer Formula
    else
      bf = (86.010 * Math.log10(39 - 18)) - (70.041 * Math.log10(self.height)) + 36.76 # Body Fat women
      lbm = self.current_weight - (self.current_weight * bf / 100)
      bmr = 370 + 21.6 * to_kg(lbm) # Katch-McArdle
    end
    dac = bmr * 1.2 # Daily Amout of Calories
    pfc_ratio(dac, lbm, bf)
  end

  def female_dac_calculator
    if !self.waist_size.nil? && !self.hip.nil? && !self.neck.nil?
      bf = (163.205 * Math.log10(self.waist_size + self.hip - self.neck)) - (97.684 * Math.log10(self.height)) - 78.387 # Body Fat women
      lbm = self.current_weight - (self.current_weight * bf / 100)
      bmr = 370 + 21.6 * to_kg(lbm) # Katch-McArdle
    else
      bmr = (9.99 * self.current_weight) + (6.25 * self.height) - (4.92 * self.age) - 161 # Mifflins-St-Joer Formula
    end
    dac = bmr * 1.2 # Daily Amout of Calories
    pfc_ratio(dac, lbm, bf)
  end

  def diet_calculator
    return male_dac_calculator if gender == 'male'
    return female_dac_calculator if gender == 'female'
  end

end

app/controllers/biometrics_controller.rb
class BiometricsController < ApplicationController
# before_action :current_user, only: :edit
before_action :authorize

  def index
    @biometric = current_user
  end

  def show
    @biometric = Biometric.find(params[:id])
  end

  def new
    @biometric = Biometric.new
  end

  def edit
     @biometric = current_user.biometric
  end

  def create
    @biometric = Biometric.new(biometric_params)
    @biometric.user = current_user

    if @biometric.save!
      @biometric.diet_calculator
      redirect_to biometrics_path
    else
      render 'new'
    end
  end

  def update
    @biometric = Biometric.find(params[:id])

    if @biometric.update(biometric_params)
      redirect_to biometrics_path
    else
      render 'edit'
    end
  end

  def destroy
    @biometric = Biometric.find(params[:id])
    @biometric.destroy

    redirect_to biometrics_path
  end

  private
    def biometric_params
      params.require(:biometric).permit(:gender, :age, :height, :current_weight, :goal_weight, :waist_size, :neck, :hip, :activity, :body_type, :goal, :diet)
    end
end

app/helpers/biometrics_helper.rb
module BiometricsHelper
end

app/views/biometrics/_form.html.erb
<%= form_for @biometric do |f| %>

  <% if @biometric.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@biometric.errors.count, "error") %> prohibited
        these biometrics from being saved:
      </h2>
      <ul>
        <% @biometric.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group row">
  <div class="biometric-step col-md-2">
    <h4>Step 1</h4>
  </div>
  <div class="col-md-10">
    <div class="form-inline mb-2">
        <legend class="col-sm-2">Gender</legend>
        <div class="form-check col-sm-3">
          <label class="form-check-label">
            <input type="radio" class="form-check-input" name="biometric[gender]" id="gender_male" value="male" checked>Male</label>
        </div>
        <div class="form-check col-sm-4">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="biometric[gender]" id="gender_female" value="female">Female</label>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="form-group">
      <label for="weight" class="col-sm-2 col-form-label col-form-label">Weight</label>
      <div class="col-sm-2">
        <input name="biometric[current_weight]" type="number" class="form-control form-control-lg" id="weight" placeholder="lbs">
      </div>
      <label for="age" class="col-sm-2 col-form-label col-form-label">Age</label>
      <div class="col-sm-2">
        <input name="biometric[age]" type="number" class="form-control form-control-lg" id="age" placeholder="yrs">
      </div>
      <label for="height" class="col-sm-1 col-md-offset-1 col-form-label col-form-label-lg">Height:</label>
      <div class="col-sm-2">
        <input name="biometric[height]" type="range" id="height" min="38" max="95">
      </div>
    </div>
  </div>
</div>

<div class="form-group row">
  <div class="biometric-step col-md-2">
    <h4>Step 2</h4>
  </div>
  <div class="col-md-10">
    <label for="waist_size" class="col-sm-2 col-form-label col-form-label">Waist Size</label>
    <div class="col-sm-2">
      <input name="biometric[waist_size]" type="number" class="form-control form-control-lg" id="waist_size" placeholder="inches">
    </div>

    <label for="neck" class="col-sm-2 col-form-label col-form-label">Neck Size</label>
    <div class="col-sm-2">
      <input name="biometric[neck]" type="number" class="form-control form-control-lg" id="neck" placeholder="inches">
    </div>

    <label for="hip_size" class="col-sm-2 col-form-label col-form-label">Hip Size</label>
    <div class="col-sm-2">
      <input name="biometric[hip]" type="number" class="form-control form-control-lg" id="hip_size" placeholder="inches">
    </div>
  </div>
</div>

<div class="form-group row">
  <div class="biometric-step col-md-2">
    <h4>Step 3</h4>
  </div>
  <div class="col-md-10">
    <label for="activity" class="col-sm-2 p-rt-0">Current Activity</label>
    <select name="biometric[activity]" class="custom-select col-sm-2" id="activity">
      <option selected>Choose...</option>
      <option value="1.2">Little To No Exercise</option>
      <option value="1.375">Light Exercise</option>
      <option value="1.55">Moderate Exercise</option>
      <option value="1.725">Heavy Exercise</option>
      <option value="1.9">Very Heavy Exercise</option>
    </select>

    <label for="goal" class="col-sm-2">Diet Goal</label>
    <select name="biometric[goal]" class="custom-select col-sm-2" id="goal">
      <option selected>Choose...</option>
      <option value="1">To Gain Weight</option>
      <option value="2">To Lose Weight</option>
      <option value="3">To Maintain</option>
      <option value="4">Increase Strength</option>
      <option value="5">Increase Performance</option>
    </select>

    <label for="goal_weight" class="col-sm-2 col-form-label col-form-label">Goal Weight</label>
    <div class="col-sm-2">
      <input name="biometric[goal_weight]" type="number" class="form-control form-control-lg" id="goal_weight" placeholder="lbs">
    </div>
  </div>
</div>

<div class="form-group row step-4">
  <div class="biometric-step col-md-2">
    <h4>Step 4</h4>
  </div>
  <div class="col-md-10 step-4">
    <label for="diet" class="col-sm-2">Diet Goal</label>
    <select name="biometric[diet]" class="custom-select col-sm-2" id="diet">
      <option selected>Choose...</option>
      <option value="1">Basic Nutrition Diet</option>
      <option value="2">Atkins Diet</option>
      <option value="3">Paleo Diet</option>
      <option value="4">Vegan</option>
    </select>

    <label for="body_type" class="col-sm-2">Body Type</label>
    <select name="biometric[body_type]" class="custom-select col-sm-2" id="body_type">
      <option selected>Choose...</option>
      <option value="1">Ectomorph</option>
      <option value="2">Mesomorph</option>
      <option value="3">Endomorph</option>
    </select>
    <span class="col-md-2"><%= image_tag'https://shapescale.com/blog/wp-content/uploads/sites/5/2016/11/Screen-Shot-2016-11-18-at-10.19.04-AM.png', id: 'image_id' %></span class="col-md-2">
  </div>
</div>
<div class="submit-btn">
  <%= f.submit class: "button" %>
</div>






    <!-- <p>
      <center><%= f.label :gender %></center><br>
      <%= f.select :gender, ['Male', 'Female']%>
    </p>
  <br>
  <p>
    <center><%= f.label :age %></center><br>
    <%= f.text_field :age %>
  </p>
  <br>
  <p>
    <center><%= f.label :height_in_inches %></center><br>
    <%= f.text_field :height %>
  </p>
  <br>
  <p>
    <center><%= f.label :current_weight_in_pounds %></center><br>
    <%= f.text_field :current_weight %>
  </p>
  <br>
  <p>
    <center><%= f.label :goal_weight_in_pounds %></center><br>
    <%= f.text_field :goal_weight %>
  </p>
  <br>
  <p>
    <center><%= f.label :waist_size_in_inches %></center><br>
    <%= f.text_field :waist_size %>
  </p>
  <br>
  <p>
    <center><%= f.label :activity %></center><br>
    <%= f.select :activity, [['Little To No Exercise', 1.2 ], ['Light Exercise', 1.375], ['Moderate Exercise', 1.55], ['Heavy Exercise', 1.725], ['Very Heavy Exercise', 1.9]] %>
  </p>
  <br>
    <center><%= f.label :neck_size_in_inches %></center><br>
    <%= f.text_field :neck %>
  </p>
  <br>
  <p>
    <center><%= f.label :hip_size_in_inches %></center><br>
    <%= f.text_field :hip %>
  </p>
  <br>
  <p>
    <center><%= f.label :body_type %></center><br>
    <center><%= image_tag'https://shapescale.com/blog/wp-content/uploads/sites/5/2016/11/Screen-Shot-2016-11-18-at-10.19.04-AM.png', id: 'image_id' %></center><br>
    <%= f.select :body_type, [['Ectomorph', '1'], ['Mesomorph', '2'],['Endomorph', '3']] %>
  </p>
  <br>
  <p>
    <center><%= f.label :goal %></center><br>
    <%= f.select :goal, [['To Gain Weight', '1'], ['To Lose Weight', '2'], ['To Maintain', '3'], ['Increase Strength', '4'], ['Increase Performance', '5']] %>
  </p>
  <br>
  <p>
    <center><%= f.label :diet %></center><br>
    <%= f.select :diet, [['Basic Nutrition Diet', '1'], ['Atkins Diet', '2'], ['Paleo Diet', '3'], ['Vegan Diet', '4']] %>
  </p>
  <br>
  <p>
    <%= f.submit class: "button" %>
  </p> -->

<% end %>

app/views/biometrics/_form2.html.erb
<%= form_for @biometric do |f| %>

  <% if @biometric.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@biometric.errors.count, "error") %> prohibited
        these biometrics from being saved:
      </h2>
      <ul>
        <% @biometric.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">


    <!-- Wrapper for slides -->
    <div class="carousel-inner center_div" role="listbox">
      <div class="item active">

          <div class="form-group">
            <label for="Gender", class="col-sm-2 col-sm-offset-3 control-label">Gender</label>
            <div class="col-sm-7">
          <%= f.text_field :gender, class: "form-control", style: "width: 30%;" %>
          </div>
        </div>

        <div class="form-group">
          <label for="Height", class="col-sm-2 col-sm-offset-3 control-label">Height</label>
          <div class="col-sm-7">
        <%= f.text_field :height, class: "form-control", style: "width: 30%;" %>
        </div>
      </div>

        <div class="form-group">
          <label for="Current_Weight", class="col-sm-2 col-sm-offset-3 control-label">Current Weight</label>
          <div class="col-sm-7">
        <%= f.text_field :current_weight, class: "form-control", style: "width: 30%;" %>
        </div>
      </div>

        <div class="form-group">
          <label for="Goal_weight", class="col-sm-2 col-sm-offset-3 control-label">Goal Weight</label>
          <div class="col-sm-7">
        <%= f.text_field :goal_weight, class: "form-control", style: "width: 30%;" %>
        </div>
      </div>

        <div class="form-group">
          <label for="Waist_size", class="col-sm-2 col-sm-offset-3 control-label">Waist Size</label>
          <div class="col-sm-7">
        <%= f.text_field :waist_size, class: "form-control", style: "width: 30%;" %>
        </div>
      </div>
      </div>


    <!-- second half of form   -->
      <div class="item">
        <div class="form-group">
          <label for="Activity", class="col-sm-2 col-sm-offset-3 control-label">Activity</label>
          <div class="col-sm-7">
        <%= f.text_field :activity, class: "form-control", style: "width: 30%;" %>
        </div>
      </div>

      <div class="form-group">
        <label for="Body_type", class="col-sm-2 col-sm-offset-3 control-label">Body Type</label>
        <div class="col-sm-7">
      <%= f.text_field :body_type, class: "form-control", style: "width: 30%;" %>
      </div>
    </div>


      <div class="form-group">
        <label for="Goal", class="col-sm-2 col-sm-offset-3 control-label">Goal</label>
        <div class="col-sm-7">
      <%= f.text_field :goal, class: "form-control", style: "width: 30%;" %>
      </div>
    </div>

      <div class="form-group">
        <label for="Diet", class="col-sm-2 col-sm-offset-3 control-label">Diet</label>
        <div class="col-sm-7">
      <%= f.text_field :diet, class: "form-control", style: "width: 30%;" %>
      </div>
    </div>


          <div class="form-group">
              <div class="col-sm-offset-5 col-sm-5">
            <%= f.submit "Submit", class: "btn btn-default" %>
          </div>
        </div>

      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

<% end %>

app/views/biometrics/edit.html.erb
<div class=container-fluid>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h2><center>Edit Your Profile</center></h2>
    </div>
  </div>
</div>
<%= render 'form' %>
<br>
<br>
<!-- <div class=container-fluid>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h5><center><%= link_to 'Back To Your Profile', biometrics_path, class:"btn btn-default new_button" %></center></h5>
    </div>
  </div>
</div> -->

app/views/biometrics/index.html.erb
<div class=container-fluid id="profile_header">
  <div class="row">
    <div class="col-md-4 col-md-offset-4" id="header_text">
      <h1><center>Your Profile</center></h1>
    </div>
  </div>
</div>
<br>
<div class='container profile'>
  <div class="row">
    <div class="col-md-2">
      <h4><center>Daily Calorie Intake</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Body Fat (%)</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Lean Body Mass</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Current Weight</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Goal Weight</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Diet</center></h4><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet_calculator["dac"].round %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet_calculator["bf"].round %>%</center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet_calculator["lbm"].round  %> lbs</center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.current_weight %> lbs</center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.goal_weight %> lbs</center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.get_diet %></center></h5><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <h4><center>Protein in Calories</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Fats in Calories</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Carbs in Calories</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Protein in Grams</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Fats in Grams</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Carbs in Grams</center></h4><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet_calculator["protein_calories"].round 2 %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet_calculator["fat_calories"].round 2 %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet_calculator["carbs_calories"].round 2 %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet_calculator["protein_grams"].round 2 %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet_calculator["fat_grams"].round 2 %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet_calculator["carbs_grams"].round 2 %></center></h5><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <h4><center>Gender</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Age</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Height</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Waist Size</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Neck Size</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Hip Size</center></h4><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.gender.capitalize %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.age %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.height %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.waist_size %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.neck %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.hip %></center></h5><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <h4><center>Activity</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Body Type</center></h4><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <h5><center><%= @biometric.get_activity.capitalize %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.get_body_type %></center></h5><br>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 col-md-offset-4">
      <h5><center><%= link_to 'Edit Your Profile', edit_biometric_path(@biometric.biometric), class:"btn btn-default new_button" %></center></h5>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <h5><center><%= link_to 'View Your Nutrition Plan', recipes_path, class:"btn btn-default new_button" %></center></h5>
    </div>
  </div>
</div>

app/views/biometrics/new.html.erb
<div class="biometric-form">
  <div class="container" style="margin-top:85px;">
    <div class="row">
      <div class="col-md-12">
        <h2><center>Now we need some info on your current health.</center></h2>
        <center>This information will be used to determine your custom nutrition plan.</center>
      </div>
    </div>

  <%= render 'form' %>

  </div>
</div>

app/views/biometrics/show.html.erb
<img src="https://www.colourbox.com/preview/2613035-healthy-food-isolated-on-a-white-background.jpg" class="img-responsive" alt="Responsive image">

<div class=container-fluid>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h2><center>Your Profile</center></h2>
    </div>
  </div>
</div>
<div class=container-fluid>
  <div class="row">
    <div class="col-md-2 col-md-offset-1">
      <h4><center>Gender</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Age</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Height</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Current Weight</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Goal Weight</center></h4><br>
    </div>
  </div>
</div>

<div class=container-fluid>
  <div class="row">
    <div class="col-md-2 col-md-offset-1">
      <h5><center><%= @biometric.biometric.gender %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.age %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.height %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.current_weight %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.goal_weight %></center></h5><br>
    </div>
  </div>
</div>

<div class=container-fluid>
  <div class="row">
    <div class="col-md-2 col-md-offset-1">
      <h4><center>Waist Size</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Activity</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Body Type</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Goal</center></h4><br>
    </div>
    <div class="col-md-2">
      <h4><center>Diet</center></h4><br>
    </div>
  </div>
</div>

<div class=container-fluid>
  <div class="row">
    <div class="col-md-2 col-md-offset-1">
      <h5><center><%= @biometric.biometric.waist_size %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.activity %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.body_type %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.goal %></center></h5><br>
    </div>
    <div class="col-md-2">
      <h5><center><%= @biometric.biometric.diet %></center></h5><br>
    </div>
  </div>
</div>

<div class=container-fluid>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h5><center><%= link_to 'Edit', edit_biometric_path(@biometric.biometric), class:"btn btn-default new_button" %></center></h5>
    </div>
  </div>
</div>