config/routes.rb
Rails.application.routes.draw do

  get 'nutrition/index'

  resources :recipes
  resources :biometrics
  resources :nutrition
  root 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get 'viewall' => 'recipes#view'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nutriprep</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-default navbar-fixed-top" id="navigation">
        <div class="container">
          <strong><%= image_tag "madang-logo.png", id: "madang-logo" %><%= link_to "NutriPrep", welcome_index_path, class: 'logo' %></strong>
          <% if current_user %>
            <%= link_to "Logout", '/logout' %>
          <% else %>
            <%= link_to 'Login', '/login' %>  <%= link_to 'Signup', '/signup' %>
          <% end %>
          <%= link_to "Profile", biometrics_path %>
          <%= link_to "Customized Nutrition Plan", recipes_path %>
          <%= link_to "Eating Right For Your Type", nutrition_index_path %>
        </div>
      </nav>

      <%= yield %>

      <footer>
        <div class="top-footer">
          <div class="container">
            <div class="row">
              <div class="col-xs-12 col-sm-2 col-sm-offset-1">
                <figure>
                  <a class="img-responsive" href="http://s1.madang.kenzap.com/" title="Madang" rel="home"><img src="<%= asset_path( 'madang-logo-white.png' ) %>" alt="Madang"></a>
                </figure>
              </div>
              <div class="col-xs-12 col-sm-2 footer-social-links pull-right">
                <ul>
                  <li><a href="#"><i class="fa fa-facebook hvr-wobble-top txcolor" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter hvr-wobble-top txcolor" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fa fa-youtube hvr-wobble-top txcolor" aria-hidden="true"></i></a>
                  </li><li><a href="#"><i class="fa fa-linkedin hvr-wobble-top txcolor" aria-hidden="true"></i></a></li>                                        <li><a href="#"><i class="fa fa-instagram txcolor hvr-wobble-top" aria-hidden="true"></i></a></li>
                </ul>
              </div>
              <div class="col-xs-12 col-sm-6 footer-menu">
                <div class="row">
                  <div class="col-xs-12 col-sm-3 footer-links">
                    <span>Nutrition</span>
                      <ul class="list-unstyled">
                        <li class="menu-item"><a href="http://s1.madang.kenzap.com/sample-menu-builder/" class="menu-link sub-menu-link">Sample Menu</a></li>
                        <li class="menu-item"><a href="http://s1.madang.kenzap.com/contact-us-builder/" class="menu-link sub-menu-link">Contact us</a></li>
                      </ul>
                  </div>
                  <div class="col-xs-12 col-sm-3 footer-links menu-item">
                    <span>Products</span>
                      <ul class="list-unstyled">
                        <li class="menu-item"><a href="http://s1.madang.kenzap.com/products-grid-builder/" class="menu-link sub-menu-link">Grid Builder</a></li>
                        <li class="menu-item"><a href="http://s1.madang.kenzap.com/program-single-builder/" class="menu-link sub-menu-link">Single Builder</a></li>
                      </ul>
                  </div>
                  <div class="col-xs-12 col-sm-3 footer-links menu-item">
                    <span>Pricing</span>
                      <ul class="list-unstyled">
                        <li class="menu-item"><a href="http://s1.madang.kenzap.com/program-builder/" class="menu-link sub-menu-link">Programs</a></li>
                        <li class="menu-item"><a href="http://s1.madang.kenzap.com/special-deals-builder/" class="menu-link sub-menu-link">Special Deals</a></li>
                      </ul>
                  </div>
                  <div class="col-xs-12 col-sm-3 footer-links menu-item ">
                    <span>Support</span>
                      <ul class="list-unstyled">
                        <li class="menu-item"><a href="http://s1.madang.kenzap.com/consultation-builder/" class="menu-link sub-menu-link">Consultation</a></li>
                        <li class="menu-item"><a href="http://s1.madang.kenzap.com/about-us-builder/" class="menu-link sub-menu-link">About Us</a></li>
                      </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="bottom-footer">
          <div class="copyright-text text-center">© 2017 NutriPrep. ALL RIGHTS RESERVED.</div>
        </div>
      </footer>
    </div>

      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>